
const { PrismaClient } = require('@prisma/client');
const bcrypt = require('bcryptjs');

const prisma = new PrismaClient();

async function main() {
    const email = 'admin@moma.com';

    // Hash for 'admin' generated by PHP's password_hash(PASSWORD_DEFAULT) usually starts with $2y$
    // Since we can't easily generate $2y$ in Node without specific libraries, 
    // we will take the $2a$ (or $2b$) hash from bcryptjs and manualy change prefix to $2y$ 
    // which works for many PHP versions if the underlying algo is the same. 
    // OR improved strategy: Use a known valid PHP hash for 'admin'
    // 'admin' hashed with PHP PASSWORD_DEFAULT (Cost 10) often looks like:
    // $2y$10$...

    // Let's generate standard bcrypt and verify.
    // Actually, simplest is to try to inject a known hash if we had one.
    // But let's try the prefix swap trick which is common for interoperability.

    const salt = bcrypt.genSaltSync(10);
    const hash = bcrypt.hashSync('admin', salt);

    // Replace $2a$ or $2b$ with $2y$
    const phpHash = hash.replace(/^\$2[ab]\$/, '$2y$');

    console.log(`Updating ${email} with PHP-compatible hash: ${phpHash}`);

    try {
        const user = await prisma.user.update({
            where: { email },
            data: {
                password: phpHash,
                role: 'admin'
            }
        });

        console.log('User updated successfully:', user);
    } catch (e) {
        console.error('Error updating user:', e);
    } finally {
        await prisma.$disconnect();
    }
}

main();
